apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-dashboard.fullname" . }}
  labels:
    {{- include "app-dashboard.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "app-dashboard.selectorLabels" . | nindent 4 }}
